edition = "2021"
max_width = 120
array_width = 100
chain_width = 60
fn_call_width = 100
fn_params_layout = "Compressed"
match_arm_leading_pipes = "Preserve"
merge_derives = false
reorder_modules = false
short_array_element_width_threshold = 32
